quizz:
    resource: "@QuizzBundle/Controller/"
    type:     annotation
    prefix:   /quizz

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

cms:
    resource: "@CmsBundle/Controller/"
    type:     annotation
    prefix:   /

#FoS
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"



